### ISSUE TITLE
Unmarshalling error while fetching the block at height 311040

### ISSUE THREAD

**Issue by pienkowb** [celo-org/kliento#16]
When I try to fetch the block at height 311040 using the `Eth.BlockByNumber` function, the following error is returned:

```
math/big: cannot unmarshal "\"0x7a772fbbbc7077ce7f7ffe\"" into a *big.Int
```
It's worth noting that the function works perfectly fine for other heights.

Example code:

```go
package main

import (
	"context"
	"log"
	"math/big"

	kliento "github.com/celo-org/kliento/client"
)

func main() {
	client, err := kliento.Dial("[NODE URL]")
	if err != nil {
		log.Fatal(err)
	}

	ctx := context.Background()
	height := big.NewInt(311040)

	_, err = client.Eth.BlockByNumber(ctx, height)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by pienkowb** [comment]
I think it is related to this issue: https://github.com/celo-org/celo-blockchain/issues/1574

**Comment by jpjamipark** [comment]
This bug was resolved in this PR: https://github.com/celo-org/celo-blockchain/pull/1688.

**Comment by pienkowb** [comment]
That solved the issue, thanks!
