### ISSUE TITLE
https://pkg.go.dev/github.com/celo-org/kliento@v0.2.1/client exists but there is no v0.2.1 tag in this repo, causing dependabot to fail

### ISSUE THREAD

**Issue by nyetwurk** [celo-org/kliento#31]
Dependabot fails to run for anything that uses kliento because pkg.go.dev declares v0.2.1 exists. However, it does not exist in this repo.

```
go: github.com/celo-org/kliento@v0.2.1: reading github.com/celo-org/kliento/go.mod at revision v0.2.1: unknown revision v0.2.1
```

https://pkg.go.dev/github.com/celo-org/kliento@v0.2.1/client

The latest tag here is v0.2.0 which is broken: 
```
github.com/celo-org/kliento/registry imports
github.com/ethereum/go-ethereum/contract_comm/errors: module github.com/ethereum/go-ethereum@latest found (v1.13.4), but does not contain package github.com/ethereum/go-ethereum/contract_comm/error
```

**Comment by nyetwurk** [comment]
as of this writing, `github.com/celo-org/kliento v0.2.1-0.20230912125702-70113468d45f` seems to work.

**Comment by palango** [comment]
@nyetwurk Yes, we haven't created a new tag, please use `v0.2.1-0.20230912125702-70113468d45f`.

What are you using kliento for?

**Comment by nyetwurk** [comment]
`client.BalanceAt()`

**Comment by palango** [comment]
@nyetwurk I pushed the tag for v0.2.1.
Please reopen if this doesn't solve your problem.

**Comment by nyetwurk** [comment]
```
# github.com/celo-org/kliento/registry
../../../go/pkg/mod/github.com/celo-org/kliento@v0.2.1/registry/registry.go:38:30: undefined: params.RegistrySmartContractAddress
../../../go/pkg/mod/github.com/celo-org/kliento@v0.2.1/registry/registry.go:159:27: undefined: params.RegistrySmartContractAddress
```

**Comment by nyetwurk** [comment]
v1.10.15 is broken
```
module declares its path as: github.com/ethereum/go-ethereum
	       but was required as: github.com/celo-org/celo-blockchain
```

**Comment by nyetwurk** [comment]
Rolling back to v1.5.0 works, but that seems super old.

**Comment by nyetwurk** [comment]
v1.7.4 works.

**Comment by palango** [comment]
> ```
> # github.com/celo-org/kliento/registry
> ../../../go/pkg/mod/github.com/celo-org/kliento@v0.2.1/registry/registry.go:38:30: undefined: params.RegistrySmartContractAddress
> ../../../go/pkg/mod/github.com/celo-org/kliento@v0.2.1/registry/registry.go:159:27: undefined: params.RegistrySmartContractAddress
> ```
> 
> Using github.com/celo-org/celo-blockchain v1.8.0, trying v1.10.15 now

Weird, this is exactly what rosetta uses:
https://github.com/celo-org/rosetta/blob/master/go.mod#L6C1-L7C66

**Comment by nyetwurk** [comment]
I also can't figure out why go thinks `v1.10.15` is a valid version.

**Comment by nyetwurk** [comment]
`RegistrySmartContractAddress` definitely disappeared in `v1.8.0`

**Comment by nyetwurk** [comment]
Ah, thats in `config` not `params` now, looks like.

**Comment by nyetwurk** [comment]
Weird
https://github.com/celo-org/kliento/blob/v0.2.1/registry/registry.go#L39C1-L39C58

Why is go importing a different version of v0.2.1?

**Comment by palango** [comment]
This is weird, let me look into it. For now resort to using `v0.2.1-0.20230912125702-70113468d45f`.

**Comment by nyetwurk** [comment]
I think go's proxy has the ancient version of v0.2.1 
for ref, my go sum entries
```
github.com/celo-org/kliento v0.2.1 h1:I81PmshPbATiSc+CsY6CUDMbtKnXl+ZNNFv/qkwuYIs=
github.com/celo-org/kliento v0.2.1/go.mod h1:w+/Q0vUdDfWg6n3Pra8bnwxw1NStG2hxoPAomvnCY/Y=
```
```
github.com/celo-org/kliento v0.2.1-0.20230912125702-70113468d45f h1:ITkZ/94WqeMio54DYQzfcFDZBkUAogncZyKXXu0FWkk=
github.com/celo-org/kliento v0.2.1-0.20230912125702-70113468d45f/go.mod h1:jp7HC2Sh7VUuGzmVUrX/4/TUz8MEPI2Qb6q6esIZhN0=
```

**Comment by palango** [comment]
Ok, I retagged it as `v0.2.2`. That has the same hash as `github.com/celo-org/kliento v0.2.1-0.20230912125702-70113468d45f/go.mod h1:jp7HC2Sh7VUuGzmVUrX/4/TUz8MEPI2Qb6q6esIZhN0=`.

So feel free to use that.

**Comment by nyetwurk** [comment]
Thank you! This resolved all of our issues.
