### ISSUE TITLE
Calling contracts

### ISSUE THREAD

**Issue by silentlight** [celo-org/kliento#4]
How can I use contracts ie. https://github.com/celo-org/kliento/blob/master/contracts/gen_blockchainparameters.go

I am trying with 

```
_, err = regClient.GetAttestationsContract(ctx, big.NewInt(2300000))
```

but I am getting `header not found` error

when I decrease height number I get

`missing trie node 7ed2e68b9d93341c40bb8e89bd6e5e553456d28f7239d028a280fd5f0b4ccc1a (path )` error

**Comment by barbaraliau** [comment]
@silentlight are you connected to a node? Also, Kliento is not maintained as an active tool for developers. We recommend using ContractKit instead, which provides a better interface for interacting with Celo Core contracts. The documentation is [here](https://docs.celo.org/developer-guide/overview/introduction/contractkit).

**Comment by silentlight** [comment]
Yeah I am connected to our node. I think we will just switch to ContractKit. Thanks

**Comment by barbaraliau** [comment]
Sounds good!
